# 欢迎使用 Jekyll！
#
# 此配置文件用于影响整个博客的设置，
# 这些值通常只需设置一次，之后很少需要编辑。
# 如果您发现自己经常编辑此文件，
# 请考虑使用 Jekyll 的数据文件功能来处理需要频繁更新的数据。
#
# 由于技术原因，当您使用 'bundle exec jekyll serve' 时，
# 此文件不会自动重新加载。如果更改此文件，请重启服务器进程。
#
# 如果您需要 YAML 语法帮助，这里有一些快速参考：
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# 网站设置
# 这些用于个性化您的新网站。如果您查看 HTML 文件，
# 您会看到它们通过 {{ site.title }}、{{ site.email }} 等方式被访问。
# 您可以创建任何自定义变量，它们将通过 {{ site.myvariable }} 
# 在模板中访问。

title: 上官玖梦
cosplay_name:
  en: ShangguanJumern
  zh: 上官玖梦
email: shangguan@jumern.com
wechat: jumernn
qq: 2099212720
since: 2023  # 建站起始年份
owner: 上官玖梦 # 版权所有者
copyright_text: "未经授权严禁转载与使用" # 版权信息
description: >- # 这表示忽略换行符，直到"baseurl:"
  这里是上官玖梦的个人网站。
  包含个人CosPlay作品展示、摄影摄像作品展示等内容。
# baseurl: "" # 您网站的子路径，例如：/blog
# url: "" # 您网站的基础主机名和协议，例如：http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# 构建设置
theme: dark-minima
plugins:
  - jekyll-feed
  - jekyll-spaceship

# 排除处理
# 默认情况下，以下项目将不会被处理。
# 在此处 `exclude:` 下列出的任何项目都将自动添加到
# 内部的"默认列表"中。
#
# 可以通过在 `include:` 列表中明确列出目录或
# 其条目的文件路径来处理被排除的项目。
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

jekyll-spaceship:
  # 默认启用的处理器
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
    optimize: # 在构建阶段优化以检查和添加 mathjax 脚本
      enabled: true # 值为 `false` 时添加到所有页面
      include: []   # 数学表达式检查的包含模式 (正则表达式)
      exclude: []   # 数学表达式检查的排除模式 (正则表达式)
  plantuml-processor:
    mode: default  # 模式值为 'pre-fetch' 时在构建阶段获取图像
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # 模式值为 'pre-fetch' 时在构建阶段获取图像
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/